#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    Potent,         sensorPotentiometer)
#pragma config(Sensor, in3,    lineSLeft,      sensorLineFollower)
#pragma config(Sensor, in4,    lineSmiddle,    sensorReflection)
#pragma config(Sensor, in5,    lineSRight,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  QuadEncRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QuadEncLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, touch,          sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                               - Verkefni 4 Bergur og Kristberg -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*   In this assignment we programmed the robot so it would't crash into objects such as walls and    *|
|*   such. The robot will turn to the right if the robot is within 35cm of the object.                *|
|*   Also in this program did we program the robot to stop all tasks if the lights in the room where  *|
|*   turned off.                                                                                      *|
\*----------------------------------------------------------------------------------------------------*/



#include "./functions/motor_functions.c";

task no_collision()
{
	while(true){

		while(SensorValue(sonarSensor) > 35  || SensorValue(sonarSensor) == -1)
		{
			motor[rightMotor] = 63;
			motor[leftMotor]  = 63;
		}
		resetEncoder();
		turn(120,true);
	}
}

task main()
{
	while(true){

		if(SensorValue(lightSensor) < 200)
		{
			StartTask(no_collision);
		}
		else{
			StopTask(no_collision);
		}
	}
}
