#pragma config(Sensor, in1,    lightSens,      sensorReflection)
#pragma config(Sensor, in2,    Potent,         sensorPotentiometer)
#pragma config(Sensor, in3,    lineSLeft,      sensorLineFollower)
#pragma config(Sensor, in4,    lineSmiddle,    sensorReflection)
#pragma config(Sensor, in5,    lineSRight,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  QuadEncRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QuadEncLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl11, touch,          sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "./functions/motor_functions.c";  //We include the file motor_functions to get the drive and turn funtions

//*We programed and emergency stop button in the task "end"//
task end()
{
	while(true)
	{
		if(vexRT[Btn8R]==1)	{StopAllTasks();}
	}
}



task main()
{
	StartTask(end);
	resetEncoder();			//We reset the encoder
	drive(564, true);   //Make the Robot drive 500cm forwards
	resetEncoder();     //We reset the encoder
	turn(120,true);			//Make the Robot turn 90° IRL
	resetEncoder();     //We reset the encoder
	drive(564, true);   //Make the Robot drive 500cm forwards
	resetEncoder();     //We reset the encoder
	turn(90,false);			//Make the Robot turn 90° IRL
	resetEncoder();     //We reset the encoder
	drive(564, true);   //Make the Robot drive 500cm forwards
	resetEncoder();     //We reset the encoder
	turn(90,false);			//Make the Robot turn 90° IRL
	resetEncoder();     //We reset the encoder
	drive(564, true);   //Make the Robot drive 500cm forwards
}
