#pragma config(Sensor, in1,    lightSens,      sensorReflection)
#pragma config(Sensor, in2,    Potent,         sensorPotentiometer)
#pragma config(Sensor, in3,    lineSLeft,      sensorLineFollower)
#pragma config(Sensor, in4,    lineSmiddle,    sensorReflection)
#pragma config(Sensor, in5,    lineSRight,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  QuadEncRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QuadEncLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl11, touch,          sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                               - Verkefni 3 Bergur og Kristberg -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*   In this assignment we programed a controler for the clawbot. to work the robot we aplied these   *|
|*   controler configurations. The right pin ch2 vertigal movement makes the robot go forwards and    *|
|*   backwards, ch2 horizontal makes the robot turn left and right. button 6U makes the claw close    *|
|*   and button 6D makes the claw open. button 5U makes the arm go down. button 5D makes the arm go up*|
\*----------------------------------------------------------------------------------------------------*/

task claw()
{ while(true){
		if(vexRT[Btn6U] == 1)
		{
		motor[clawMotor] = -60;
		}
		if(vexRT[Btn6D] == 1)
		{
		motor[clawMotor] = 60;
		}
		else
		{
		motor[clawMotor] = 0;
		}
	}
}

task arm()
{
	while(true){
		if(vexRT[Btn5U] == 1)
		{
		motor[armMotor] = 127;
		}
		if(vexRT[Btn5D] == 1)
		{
		motor[armMotor] = -127;
		}
		else
		{
		motor[armMotor] = 0;
		}
	}
}

task main()
{
	StartTask(arm);
	StartTask(claw);
  while(1 == 1)
	{
		if(vexRT[Btn6U] == 1)
		{
			StopTask(arm);
			StartTask(claw);
		}

		if(vexRT[Btn5U] == 1)
		{
			StopTask(claw);
			StartTask(arm);
		}

		motor[rightMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[leftMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;
	}
}
