

/*----------------------------------------------------------------------------------------------------*\
|*                               - Verkefni 2 hluti 2 Bergur og Kristberg -                           *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*   In this program we make the robot drive forwards 500cm then drive backwards 500cm then 1m        *|
|*   forwards then after that drive 1m backwards again and do this until its 2.5m after that the      *|
|*   program stops. And in this program we make the robot drive strait                                *|                                                     *|
|*                                                                                                    *|
\*----------------------------------------------------------------------------------------------------*/



#pragma config(Sensor, in1,    lightSens,      sensorReflection)
#pragma config(Sensor, in2,    Potent,         sensorPotentiometer)
#pragma config(Sensor, in3,    lineSLeft,      sensorLineFollower)
#pragma config(Sensor, in4,    lineSmiddle,    sensorReflection)
#pragma config(Sensor, in5,    lineSRight,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  QuadEncRight,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QuadEncLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl11, touch,          sensorTouch)
#pragma config(Motor,  port2,           leftMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//(50/2,54*4*3,14)360=disT
void resetEncoder(){
	SensorValue[QuadEncLeft]=0;
	SensorValue[QuadEncRight]=0;

}
const int DIST=564;
void drive(int dist,bool bf){
	int multiplier = (bf)?(1):(-1);
	while( dist > abs(SensorValue[QuadEncLeft])){
		if(abs(SensorValue[QuadEncLeft]) == abs(SensorValue[QuadEncRight])) // If rightEncoder has counted the same amount as leftEncoder:
		{
			// Move Forward
			motor[leftMotor] = 80*multiplier;		    // Right Motor is run at power level 80
			motor[rightMotor]  = 80*multiplier;		    // Left Motor is run at power level 80
		}
		else if(abs(SensorValue[QuadEncLeft]) > abs(SensorValue[QuadEncRight]))	// If rightEncoder has counted more encoder counts
		{
			// Turn slightly right
			motor[leftMotor] = 60*multiplier;		    // Right Motor is run at power level 60
			motor[rightMotor]  = 80*multiplier;		    // Left Motor is run at power level 80
		}
		else	// Only runs if leftEncoder has counted more encoder counts
		{
			// Turn slightly left
			motor[leftMotor] = 80*multiplier;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 60*multiplier;		    // Left Motor is run at power level 60
		}
	}

}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);
	for(int i = 1; i < 5; i++){
		resetEncoder();
		drive(i*DIST,true);
		resetEncoder();
		drive(i*DIST,false);

	}



}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
