#pragma config(Sensor, in1,    lightSens,      sensorReflection)
#pragma config(Sensor, in2,    Potent,         sensorPotentiometer)
#pragma config(Sensor, in3,    lineSLeft,      sensorLineFollower)
#pragma config(Sensor, in4,    lineSmiddle,    sensorReflection)
#pragma config(Sensor, in5,    lineSRight,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  QuadEnc1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  QuadEnc2,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl11, touch,          sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
const int DRIVETIME = 1000;

void drive_forward(int i){
	motor[rightMotor] = 127;
	motor[leftMotor]  = 127;
	wait1Msec(DRIVETIME*i);

}
void drive_backwards(int i){
	motor[rightMotor] = -127;
	motor[leftMotor]  = -127;
	wait1Msec(DRIVETIME*i);

}
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);
	for(int i = 1; i < 5; i++){
		drive_forward(i);
		drive_backwards(i);

	}



}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
